services:
  mongodb:
    build:
      context: ./mongo
      dockerfile: dockerfile
    ports:
      - "27017:27017"
    volumes:
       # The official docker image requires a certain way for initial collections, users are created
       # Must be an absolute path
      - ./mongo/docker-entrypoint-initdb.d/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - 'mongodb_data:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=testdatabase
    networks:
      - testnet

  go:
    build:
      context: ./go
      dockerfile: dockerfile
    ports:
      - '443:443'
    depends_on:
      - mongodb
    networks:
      - testnet
    restart: unless-stopped

  rust:
    build:
      context: ./rust
      dockerfile: dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    networks:
      - testnet
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  testnet:
    driver: bridge