services:
  mongodb:
    image: bitnami/mongodb:7.0.9
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_USER=rootuser
      - MONGODB_ROOT_PASSWORD=rootpass
      - MONGODB_USERNAME=testuser
      - MONGODB_PASSWORD=testpass
      - MONGODB_DATABASE=testdatabase
      # This is required on Apple Silicon https://github.com/docker/for-mac/issues/6620
      # https://github.com/bitnami/containers/issues/40947#issuecomment-1927013148
      - EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1
    networks:
      - testnet

  go:
    build:
      context: ./go
      dockerfile: dockerfile
    ports:
      - '443:443'
    depends_on:
      - mongodb
    networks:
      - testnet
    restart: unless-stopped

  rust:
    build:
      context: ./rust
      dockerfile: dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    networks:
      - testnet
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  testnet:
    driver: bridge