FROM golang:1.22.2

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN go clean
RUN go clean -modcache
RUN go mod download
RUN go get goserver/database

CMD ["go", "run", "httpsServer.go"]